"""Simulated wafer-shape metrology decomposition into bow, cylindrical and
saddle terms.

This is a from-scratch, low-order polynomial (quadratic-form) fit to a
simulated wafer height map, following the same canonical warpage-shape
vocabulary the FE wafer-warpage literature uses to describe how a 300mm
wafer deviates from flat: bow (an isotropic, spherical-cap curvature),
cylindrical (a direction-dependent curvature that bends more along one
axis than the perpendicular axis, an astigmatism-like term), and saddle
(a twist term where the two diagonal directions curve in opposite signs).
See "Finite-Element Simulation of Different Kinds of Wafer Warpages:
Spherical, Cylindrical, and Saddle" for the shape taxonomy this module
implements numerically.

All wafer-shape data in this module is SIMULATED. No physical wafer,
interferometer, or metrology tool was involved anywhere in this module;
every height map is generated by `synth_height_map` from injected
ground-truth coefficients, optionally with injected noise.

Model
-----
A wafer-shape metrology surface is represented as a height map z(x, y)
over normalized in-plane coordinates xn = x / R, yn = y / R (R is the
wafer radius, 150 mm for a 300mm wafer), so xn and yn each range over
roughly [-1, 1] across the wafer. Before any shape classification, a
real metrology tool always removes the rigid-body reference terms
(piston, and the two tilts) by a best-fit-plane subtraction; this module
folds that subtraction directly into the same least-squares fit rather
than doing it as a separate pass, using this basis:

    z(x, y) = piston
            + tip    * xn
            + tilt   * yn
            + bow    * (xn^2 + yn^2)
            + cyl    * (xn^2 - yn^2)
            + saddle * (xn * yn)

`bow` is the mean/isotropic curvature term (a paraboloid of revolution:
same curvature in every direction). `cyl` is the direction-dependent
curvature difference between the x and y axes (positive cyl means more
curvature along x than y); `saddle` is the same idea rotated 45 degrees,
expressed as the xy cross term (positive saddle means the +x+y and
-x-y quadrants bow one way and the +x-y / -x+y quadrants bow the other).
Together (cyl, saddle) span the same 2-dimensional "astigmatism" space;
which one a given asymmetric curvature loads onto is exactly the sign
convention this module's rotation-invariant tests below pin down.

Fitting
-------
`fit_shape_lstsq` solves the linear least-squares problem with
`numpy.linalg.lstsq` (SVD-based, numerically robust even for a
moderately ill-conditioned design matrix); this is the fit used
everywhere else in this project. `fit_shape_normal_equations` solves the
textbook normal equations (X^T X) beta = X^T z directly with
`numpy.linalg.solve`; it is the obviously-correct reference oracle this
module's tests diff the production fit against (see
`tests/test_wafer_shape.py::test_lstsq_matches_normal_equations_reference_oracle`),
not the method used for anything else, because the normal-equations
approach squares the condition number of X and is measurably less
numerically robust at high noise or a poorly-covered grid.
"""
from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

WAFER_RADIUS_MM = 150.0  # 300mm wafer

# Column order used everywhere in this module: piston, tip, tilt, bow, cyl, saddle.
TERM_NAMES = ("piston", "tip", "tilt", "bow", "cyl", "saddle")
SHAPE_TERM_NAMES = ("bow", "cyl", "saddle")  # the three classified warpage terms


@dataclass(frozen=True)
class ShapeCoeffs:
    piston: float
    tip: float
    tilt: float
    bow: float
    cyl: float
    saddle: float

    def as_vector(self) -> np.ndarray:
        return np.array([self.piston, self.tip, self.tilt, self.bow, self.cyl, self.saddle])

    def get(self, term: str) -> float:
        return getattr(self, term)

    def with_term_offset(self, term: str, offset: float) -> "ShapeCoeffs":
        values = {name: getattr(self, name) for name in TERM_NAMES}
        values[term] += offset
        return ShapeCoeffs(**values)


def make_measurement_grid(n_per_axis: int = 31, radius: float = WAFER_RADIUS_MM) -> tuple[np.ndarray, np.ndarray]:
    """A Cartesian grid over [-radius, radius] on both axes, masked to the
    wafer disk (r <= radius). This is a stand-in for a real metrology tool's
    scan pattern (interferometers commonly report on a Cartesian grid
    clipped to the wafer outline); n_per_axis=31 gives roughly 750 points
    inside a 300mm-diameter disk, enough to fit 6 coefficients with a
    well-conditioned design matrix (see test_design_matrix_is_well_conditioned)
    without the O(n^2) grid becoming slow to fit thousands of times in the
    Monte Carlo sweeps below."""
    axis = np.linspace(-radius, radius, n_per_axis)
    xx, yy = np.meshgrid(axis, axis)
    xx = xx.ravel()
    yy = yy.ravel()
    mask = xx ** 2 + yy ** 2 <= radius ** 2
    return xx[mask], yy[mask]


def design_matrix(x: np.ndarray, y: np.ndarray, radius: float = WAFER_RADIUS_MM) -> np.ndarray:
    xn = x / radius
    yn = y / radius
    return np.column_stack([
        np.ones_like(xn), xn, yn, xn ** 2 + yn ** 2, xn ** 2 - yn ** 2, xn * yn,
    ])


def synth_height_map(coeffs: ShapeCoeffs, x: np.ndarray, y: np.ndarray, radius: float = WAFER_RADIUS_MM,
                      noise_sigma: float = 0.0, rng: np.random.Generator | None = None) -> np.ndarray:
    """Generate a SIMULATED wafer height map from injected ground-truth
    shape coefficients, optionally with injected i.i.d. Gaussian per-point
    measurement noise (a stand-in for interferometer/instrument noise)."""
    X = design_matrix(x, y, radius)
    z = X @ coeffs.as_vector()
    if noise_sigma > 0.0:
        if rng is None:
            raise ValueError("rng is required when noise_sigma > 0")
        z = z + rng.normal(0.0, noise_sigma, size=z.shape)
    return z


def _vector_to_coeffs(vec: np.ndarray) -> ShapeCoeffs:
    return ShapeCoeffs(*[float(v) for v in vec])


def fit_shape_lstsq(x: np.ndarray, y: np.ndarray, z: np.ndarray, radius: float = WAFER_RADIUS_MM) -> ShapeCoeffs:
    """Production fit: SVD-based least squares via numpy.linalg.lstsq."""
    X = design_matrix(x, y, radius)
    coeffs, _residuals, _rank, _sv = np.linalg.lstsq(X, z, rcond=None)
    return _vector_to_coeffs(coeffs)


def fit_shape_normal_equations(x: np.ndarray, y: np.ndarray, z: np.ndarray,
                                radius: float = WAFER_RADIUS_MM) -> ShapeCoeffs:
    """Reference oracle: the textbook normal-equations solve, (X^T X) beta =
    X^T z, via numpy.linalg.solve. Obviously correct by construction (it is
    the closed-form least-squares solution), but not used for production
    fits because squaring the design matrix's condition number makes it a
    weaker choice at high noise; kept here specifically to diff against
    fit_shape_lstsq."""
    X = design_matrix(x, y, radius)
    xtx = X.T @ X
    xtz = X.T @ z
    coeffs = np.linalg.solve(xtx, xtz)
    return _vector_to_coeffs(coeffs)


def design_matrix_condition_number(x: np.ndarray, y: np.ndarray, radius: float = WAFER_RADIUS_MM) -> float:
    X = design_matrix(x, y, radius)
    return float(np.linalg.cond(X.T @ X))


def rotate_90(x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Coordinates after a physical +90 degree rotation of the wafer under a
    fixed measurement grid: the height that lands at grid point (x, y) is
    the original shape function evaluated at (-y, x)."""
    return -y, x


def rotate_180(x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    return -x, -y


def predict_coeffs_after_rotate_90(coeffs: ShapeCoeffs) -> ShapeCoeffs:
    """Analytic prediction for what fit_shape_lstsq recovers after a +90
    degree rotation, derived in the module docstring's basis: bow is
    invariant (isotropic curvature does not care about axis labeling); cyl
    and saddle both flip sign (a 90 degree rotation swaps the x and y axes,
    which is exactly the operation that exchanges cylindrical bending for
    its own negative and swaps which diagonal the saddle term loads onto);
    tip and tilt swap (with a sign flip on the new tip), piston is
    unchanged."""
    return ShapeCoeffs(
        piston=coeffs.piston, tip=coeffs.tilt, tilt=-coeffs.tip,
        bow=coeffs.bow, cyl=-coeffs.cyl, saddle=-coeffs.saddle,
    )


def predict_coeffs_after_rotate_180(coeffs: ShapeCoeffs) -> ShapeCoeffs:
    """Analytic prediction after a 180 degree rotation: bow, cyl and saddle
    are all invariant (every term in the basis that survives a sign flip on
    both x and y simultaneously is even-degree in each variable separately
    or a product of two flipped signs), tip and tilt flip sign, piston is
    unchanged. This is a genuinely different invariant from the 90 degree
    case (there bow was invariant but cyl/saddle flipped) and catches a
    mislabeled cyl/saddle sign convention that the 90 degree check alone
    would not (a convention bug that swaps the sign of both cyl and saddle
    consistently would still pass a 90 degree round trip if the bug were
    applied identically to the analytic prediction, but would not survive
    an independently-derived 180 degree prediction built from the same
    basis)."""
    return ShapeCoeffs(
        piston=coeffs.piston, tip=-coeffs.tip, tilt=-coeffs.tilt,
        bow=coeffs.bow, cyl=coeffs.cyl, saddle=coeffs.saddle,
    )


def max_abs_diff(a: ShapeCoeffs, b: ShapeCoeffs) -> float:
    return float(np.max(np.abs(a.as_vector() - b.as_vector())))
